const featureddata = [
    {
      id: 1,
      name: "TATA Nexon",
      image: ["https://cdni.autocarindia.com/Utils/ImageResizerV2.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Tata-Nexon-220920231520.jpeg&w=872&h=578&q=75&c=1",
        "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/141867/nexon-facelift-exterior-right-front-three-quarter-69.jpeg?isig=0&q=80&q=80",
        "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/141867/nexon-facelift-exterior-left-rear-three-quarter.jpeg?isig=0&q=80",
        "https://imgd.aeplcdn.com/664x374/n/cw/ec/141867/nexon-facelift-exterior-right-side-view.jpeg?isig=0&q=80"],
      description:"Tata Nexon boasts 5-star Global NCAP safety, advanced tech features like a touchscreen infotainment system, spacious interiors, turbocharged engine options, high ground clearance, and is ideal for both city and highway driving.",
      price:"Rs. 9 - 15.80 Lakhs",
      engine:"1199 cc - 1497 cc",
      power:"113.31 - 118.27 bhp",
      capacity: "5",
      fuel:"Petrol/Diesel/EV",
      mileage:"24.08 kmpl",
      torque:"170 Nm - 260 Nm",
      pro1: "5-star Global NCAP safety rating",
      pro2: "Comfortable ride quality: tackles bad roads with ease",
      pro3: "Affordable maintenance costs",
      con1: "Ergonomic issues still persist",
      con2: "Iffy fit and finish around certain interior panels",
      con3: "Tech package glitches time to time",
    },
    {
        id: 2,
        name: "Hyundai i20",
        image: ["https://imgd.aeplcdn.com/664x374/n/cw/ec/150603/i20-exterior-right-front-three-quarter-7.jpeg?isig=0&q=80",
                  "https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/i20/9471/1694165749301/exterior-image-165.jpg",
                  "https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/i20/9471/1694165749301/exterior-image-167.jpg",
                  "https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/i20/9471/1694165749301/rear-right-side-48.jpg"],
        description:"Hyundai i20 features a premium design, advanced infotainment system, wireless charging, sunroof, excellent fuel efficiency, and spacious interiors, making it a stylish and tech-loaded hatchback for city driving.",
        price:"Rs. 8.23 - 13.22 Lakh",
        engine:"1197 cc",
        power:"82 - 87 bhp",
        capacity: "5",
        fuel:"Petrol/Diesel",
        mileage:"16 - 20 kmpl",
        torque:"114.7 Nm",
        pro1: "Feature-rich (sunroof, digital cluster, large infotainment system)",
        pro2: "Refined and smooth engines, especially petrol",
        pro3: "Strong safety features (up to 6 airbags, ABS, ESC)",
        con1: "Higher price compared to competitors",
        con2: "Slightly lower fuel efficiency in petrol variants",
        con3: "Lower ground clearance, less suited for bad roads",
    },
  ];
  
  export default featureddata;